### ISSUE TITLE
About Tensorflow FLOPs

### ISSUE THREAD

**Issue by dujiangsu** [It4innovations/Intel-SDE-FLOPS#3]
Hi David,

This is really a useful program you developed. 

There I meet a problem when computing FLOPs of Tensorflow program. 

I ran my Tensorflow program using (sde64 -iform -mix -dyn_mask_profile -- python tf_cnn_benchmarks.py). Actually, the underlying code of TF is written by C++ and I got files 
![image](https://user-images.githubusercontent.com/12018307/54484794-ec238580-48a7-11e9-93fd-6e24e9468c6e.png). 

However, it's almost empty of these files. My tensorflow program only ran on CPU. So, do you know how can I compute flops like this?

Many thanks!

**Comment by gzitzlsb-it4i** [comment]
Hello DouJS,

thank you for reporting, and sorry for the delay. I did not get a notification of your message, but have changed that now.

I'm using Tensorflow (TF) myself and one reason for "empty" results is that if TF crashes, SDE won't write all information into the files. Could you please confirm that your Python script using TF properly exits?

Furthermore, TF creates and terminates threads during it's runtime. Those show up as the txt files with the IDs in their names (i.e. terminated threads).
You also might want to have more control on the exact location within your TF sessions to collect the FLOPS. I've made available what I'm using under the directory "for_python", which allows the SDE markers to be set within any Python script.

Please let me know how I can help you further.

Best regards,

Georg

**Comment by gzitzlsb-it4i** [comment]
Hello DouJS,

FYI: Recently I've added the option to the script to manually specify the profiling files.
This allows you to select any pair of "sde-mix-out.\*.txt" and "sde-dyn-mask-profile.\*.txt" files. This should be more appropriate in case of an execution with multiple processes and nested/terminated threads during runtime, e.g.:

$ python intel_sde_flops.py sde-mix-out.24742-24745.txt sde-dyn-mask-profile.24742-24745.txt
<output>

Best regards,

Georg

**Comment by dujiangsu** [comment]
Thanks for your detailed explanation, it is very useful. Coz I switched to use TFprofiler to measure FLOPs and I need to use sde again.
