### ISSUE TITLE
IS AVX512_BF16 being added to SDE

### ISSUE THREAD

**Issue by tks2004** [It4innovations/Intel-SDE-FLOPS#5]

**Comment by gzitzlsb-it4i** [comment]
Hello,

the current version of Intel SDE is 8.35, which implements the ISA documented in the "Intel® Architecture Instruction Set Extensions and Future Features Programming Reference" with version 319433-035 (from October 2018).

Cooper Lake's ISA, which adds AVX512_BF16, was not published back then. However, there is already the version 319433-037 (from May 2019) available:
https://software.intel.com/sites/default/files/managed/c5/15/architecture-instruction-set-extensions-programming-reference.pdf

As such, I'd expect Intel SDE to "soon" add support for BF16. Once Intel SDE provides the BF16 counters, I can add support for it to the script, too.
It's up to Intel to update the Intel SDE tool.

Best regards,

Georg

**Comment by gzitzlsb-it4i** [comment]
Since Intel SDE 8.50 supports AVX512_BF16 now, it has been added to the script (experimental in version 1.1).
